// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_adminScreen_screen_init(void)
{
    ui_adminScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_adminScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_btn_create(ui_adminScreen);
    lv_obj_set_width(ui_Button3, 400);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, 0);
    lv_obj_set_y(ui_Button3, 340);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_adminScreen);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, 340);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "BACK/CANCEL");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_adminScanButton = lv_btn_create(ui_adminScreen);
    lv_obj_set_width(ui_adminScanButton, 251);
    lv_obj_set_height(ui_adminScanButton, 50);
    lv_obj_set_x(ui_adminScanButton, 0);
    lv_obj_set_y(ui_adminScanButton, -310);
    lv_obj_set_align(ui_adminScanButton, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_adminScanButton, lv_color_hex(0xFF9800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_adminScanButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_addPrintLabel2 = lv_label_create(ui_adminScreen);
    lv_obj_set_width(ui_addPrintLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_addPrintLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_addPrintLabel2, 0);
    lv_obj_set_y(ui_addPrintLabel2, -365);
    lv_obj_set_align(ui_addPrintLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_addPrintLabel2, "ADMIN SCREEN");
    lv_obj_set_style_text_decor(ui_addPrintLabel2, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_addPrintLabel2, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_adminScanLabel = lv_label_create(ui_adminScreen);
    lv_obj_set_width(ui_adminScanLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_adminScanLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_adminScanLabel, 0);
    lv_obj_set_y(ui_adminScanLabel, -310);
    lv_obj_set_align(ui_adminScanLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_adminScanLabel, "SCAN ADMIN CARD");
    lv_obj_set_style_text_color(ui_adminScanLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_adminScanLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_adminScanLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_adminScreen);
    lv_obj_set_width(ui_Button5, 100);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_x(ui_Button5, -24);
    lv_obj_set_y(ui_Button5, -68);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);

    ui_Label9 = lv_label_create(ui_adminScreen);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -20);
    lv_obj_set_y(ui_Label9, -72);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Add Member");

    ui_Button6 = lv_btn_create(ui_adminScreen);
    lv_obj_set_width(ui_Button6, 100);
    lv_obj_set_height(ui_Button6, 50);
    lv_obj_set_x(ui_Button6, -1);
    lv_obj_set_y(ui_Button6, 88);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);

    ui_Label10 = lv_label_create(ui_adminScreen);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 8);
    lv_obj_set_y(ui_Label10, 84);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "EMPTY QUEUE");

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);

}
