// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_addMemberScreen_screen_init(void)
{
    ui_addMemberScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_addMemberScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_addMemberScreen);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 0);
    lv_obj_set_y(ui_Label11, -365);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "ADD MEMBER");
    lv_obj_set_style_text_decor(ui_Label11, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scanMemberCardButton = lv_btn_create(ui_addMemberScreen);
    lv_obj_set_width(ui_scanMemberCardButton, 277);
    lv_obj_set_height(ui_scanMemberCardButton, 50);
    lv_obj_set_x(ui_scanMemberCardButton, 0);
    lv_obj_set_y(ui_scanMemberCardButton, -235);
    lv_obj_set_align(ui_scanMemberCardButton, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_scanMemberCardButton, lv_color_hex(0xFF9800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scanMemberCardButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_addMemberScreen);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 0);
    lv_obj_set_y(ui_Label12, -235);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "SCAN MEMBER CARD");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_addMemberButton = lv_btn_create(ui_addMemberScreen);
    lv_obj_set_width(ui_addMemberButton, 400);
    lv_obj_set_height(ui_addMemberButton, 50);
    lv_obj_set_x(ui_addMemberButton, 0);
    lv_obj_set_y(ui_addMemberButton, 130);
    lv_obj_set_align(ui_addMemberButton, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_addMemberButton, lv_color_hex(0x15B700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_addMemberButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_memberScreenKeyboard = lv_keyboard_create(ui_addMemberScreen);
    lv_obj_set_width(ui_memberScreenKeyboard, 475);
    lv_obj_set_height(ui_memberScreenKeyboard, 150);
    lv_obj_set_x(ui_memberScreenKeyboard, 0);
    lv_obj_set_y(ui_memberScreenKeyboard, 322);
    lv_obj_set_align(ui_memberScreenKeyboard, LV_ALIGN_CENTER);

    ui_Label13 = lv_label_create(ui_addMemberScreen);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 0);
    lv_obj_set_y(ui_Label13, 130);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "ADD MEMBER");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_adminCheckBox = lv_checkbox_create(ui_addMemberScreen);
    lv_checkbox_set_text(ui_adminCheckBox, "Admin");
    lv_obj_set_width(ui_adminCheckBox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_adminCheckBox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_adminCheckBox, 0);
    lv_obj_set_y(ui_adminCheckBox, 60);
    lv_obj_set_align(ui_adminCheckBox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_adminCheckBox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_adminCheckBox, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_memberNameTextArea = lv_textarea_create(ui_addMemberScreen);
    lv_obj_set_width(ui_memberNameTextArea, 400);
    lv_obj_set_height(ui_memberNameTextArea, 40);
    lv_obj_set_x(ui_memberNameTextArea, 0);
    lv_obj_set_y(ui_memberNameTextArea, -110);
    lv_obj_set_align(ui_memberNameTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_memberNameTextArea, "Enter name...");



    ui_phoneNumberTextArea = lv_textarea_create(ui_addMemberScreen);
    lv_obj_set_width(ui_phoneNumberTextArea, 400);
    lv_obj_set_height(ui_phoneNumberTextArea, 40);
    lv_obj_set_x(ui_phoneNumberTextArea, 0);
    lv_obj_set_y(ui_phoneNumberTextArea, -20);
    lv_obj_set_align(ui_phoneNumberTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_phoneNumberTextArea, "Enter phone number...");



    ui_backButton = lv_btn_create(ui_addMemberScreen);
    lv_obj_set_width(ui_backButton, 400);
    lv_obj_set_height(ui_backButton, 50);
    lv_obj_set_x(ui_backButton, 0);
    lv_obj_set_y(ui_backButton, 200);
    lv_obj_set_align(ui_backButton, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_backButton, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backButtonLabel = lv_label_create(ui_addMemberScreen);
    lv_obj_set_width(ui_backButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_backButtonLabel, 0);
    lv_obj_set_y(ui_backButtonLabel, 200);
    lv_obj_set_align(ui_backButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_backButtonLabel, "BACK/CANCEL");
    lv_obj_set_style_text_color(ui_backButtonLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_backButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_backButtonLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_addMemberScreen);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 0);
    lv_obj_set_y(ui_Label14, 30);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Step 4: Should The User Be Admin? (PROBABLY NOT)");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_addMemberScreen);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 0);
    lv_obj_set_y(ui_Label15, -310);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Step 1: Scan The Members Union Card");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_addMemberScreen);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 0);
    lv_obj_set_y(ui_Label16, -150);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Step 2: Enter The Members Full Name");
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_addMemberScreen);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 0);
    lv_obj_set_y(ui_Label17, -60);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Step 3: Enter The Members Phone Number");
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_addMemberScreen);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 0);
    lv_obj_set_y(ui_Label18, -280);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "You have 5 seconds to scan the card");

    ui_scanMemberInfoLabel = lv_label_create(ui_addMemberScreen);
    lv_obj_set_width(ui_scanMemberInfoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scanMemberInfoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scanMemberInfoLabel, 0);
    lv_obj_set_y(ui_scanMemberInfoLabel, -185);
    lv_obj_set_align(ui_scanMemberInfoLabel, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_scanMemberCardButton, ui_event_scanMemberCardButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_addMemberButton, ui_event_addMemberButton, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_memberScreenKeyboard, ui_memberNameTextArea);
    lv_obj_add_event_cb(ui_memberNameTextArea, ui_event_memberNameTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_phoneNumberTextArea, ui_event_phoneNumberTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backButton, ui_event_backButton, LV_EVENT_ALL, NULL);

}
