// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_adminScreen_screen_init(void)
{
    ui_adminScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_adminScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_backCancelAdminButton = lv_btn_create(ui_adminScreen);
    lv_obj_set_width(ui_backCancelAdminButton, 400);
    lv_obj_set_height(ui_backCancelAdminButton, 50);
    lv_obj_set_x(ui_backCancelAdminButton, 0);
    lv_obj_set_y(ui_backCancelAdminButton, 340);
    lv_obj_set_align(ui_backCancelAdminButton, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_backCancelAdminButton, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backCancelAdminButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_adminScreen);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, 340);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "BACK/CANCEL");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_adminScanButton = lv_btn_create(ui_adminScreen);
    lv_obj_set_width(ui_adminScanButton, 251);
    lv_obj_set_height(ui_adminScanButton, 50);
    lv_obj_set_x(ui_adminScanButton, 0);
    lv_obj_set_y(ui_adminScanButton, -310);
    lv_obj_set_align(ui_adminScanButton, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_adminScanButton, lv_color_hex(0xFF9800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_adminScanButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_addPrintLabel2 = lv_label_create(ui_adminScreen);
    lv_obj_set_width(ui_addPrintLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_addPrintLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_addPrintLabel2, 0);
    lv_obj_set_y(ui_addPrintLabel2, -365);
    lv_obj_set_align(ui_addPrintLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_addPrintLabel2, "ADMIN SCREEN");
    lv_obj_set_style_text_decor(ui_addPrintLabel2, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_addPrintLabel2, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_adminScanLabel = lv_label_create(ui_adminScreen);
    lv_obj_set_width(ui_adminScanLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_adminScanLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_adminScanLabel, 0);
    lv_obj_set_y(ui_adminScanLabel, -310);
    lv_obj_set_align(ui_adminScanLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_adminScanLabel, "SCAN ADMIN CARD");
    lv_obj_set_style_text_color(ui_adminScanLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_adminScanLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_adminScanLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_adminScreenAddMemberButton = lv_btn_create(ui_adminScreen);
    lv_obj_set_width(ui_adminScreenAddMemberButton, 400);
    lv_obj_set_height(ui_adminScreenAddMemberButton, 50);
    lv_obj_set_x(ui_adminScreenAddMemberButton, 0);
    lv_obj_set_y(ui_adminScreenAddMemberButton, -170);
    lv_obj_set_align(ui_adminScreenAddMemberButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_adminScreenAddMemberButton, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_adminScreenAddMemberButton, lv_color_hex(0x0014FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_adminScreenAddMemberButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_adminScreen);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, -170);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "ADD MEMBER");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_adminScreenQueueManagmentButton = lv_btn_create(ui_adminScreen);
    lv_obj_set_width(ui_adminScreenQueueManagmentButton, 400);
    lv_obj_set_height(ui_adminScreenQueueManagmentButton, 50);
    lv_obj_set_x(ui_adminScreenQueueManagmentButton, 0);
    lv_obj_set_y(ui_adminScreenQueueManagmentButton, -30);
    lv_obj_set_align(ui_adminScreenQueueManagmentButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_adminScreenQueueManagmentButton, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_adminScreenQueueManagmentButton, lv_color_hex(0x7000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_adminScreenQueueManagmentButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_queueManagmentLabel = lv_label_create(ui_adminScreen);
    lv_obj_set_width(ui_queueManagmentLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_queueManagmentLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_queueManagmentLabel, 0);
    lv_obj_set_y(ui_queueManagmentLabel, -30);
    lv_obj_set_align(ui_queueManagmentLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_queueManagmentLabel, "MANAGE QUEUE");
    lv_obj_set_style_text_color(ui_queueManagmentLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_queueManagmentLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_queueManagmentLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_adminScanStatusLabel = lv_label_create(ui_adminScreen);
    lv_obj_set_width(ui_adminScanStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_adminScanStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_adminScanStatusLabel, 0);
    lv_obj_set_y(ui_adminScanStatusLabel, -270);
    lv_obj_set_align(ui_adminScanStatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_adminScanStatusLabel, "Please Scan Your Union Card");

    lv_obj_add_event_cb(ui_backCancelAdminButton, ui_event_backCancelAdminButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_adminScanButton, ui_event_adminScanButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_adminScreenAddMemberButton, ui_event_adminScreenAddMemberButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_adminScreenQueueManagmentButton, ui_event_adminScreenQueueManagmentButton, LV_EVENT_ALL, NULL);

}
