// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_addToQueueScreen_screen_init(void)
{
    ui_addToQueueScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_addToQueueScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_goToQueueScreenButton = lv_btn_create(ui_addToQueueScreen);
    lv_obj_set_width(ui_goToQueueScreenButton, 400);
    lv_obj_set_height(ui_goToQueueScreenButton, 50);
    lv_obj_set_x(ui_goToQueueScreenButton, 0);
    lv_obj_set_y(ui_goToQueueScreenButton, 340);
    lv_obj_set_align(ui_goToQueueScreenButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_goToQueueScreenButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_goToQueueScreenButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_goToQueueScreenButton, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_goToQueueScreenButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goToQueueScreenButtonLabel = lv_label_create(ui_addToQueueScreen);
    lv_obj_set_width(ui_goToQueueScreenButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_goToQueueScreenButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_goToQueueScreenButtonLabel, 0);
    lv_obj_set_y(ui_goToQueueScreenButtonLabel, 340);
    lv_obj_set_align(ui_goToQueueScreenButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_goToQueueScreenButtonLabel, "BACK/CANCEL");
    lv_obj_set_style_text_color(ui_goToQueueScreenButtonLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_goToQueueScreenButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_goToQueueScreenButtonLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goToQueueScreenButton1 = lv_btn_create(ui_addToQueueScreen);
    lv_obj_set_width(ui_goToQueueScreenButton1, 400);
    lv_obj_set_height(ui_goToQueueScreenButton1, 50);
    lv_obj_set_x(ui_goToQueueScreenButton1, 0);
    lv_obj_set_y(ui_goToQueueScreenButton1, 270);
    lv_obj_set_align(ui_goToQueueScreenButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_goToQueueScreenButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_goToQueueScreenButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_goToQueueScreenButton1, lv_color_hex(0x15B700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_goToQueueScreenButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goToQueueScreenButtonLabel1 = lv_label_create(ui_addToQueueScreen);
    lv_obj_set_width(ui_goToQueueScreenButtonLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_goToQueueScreenButtonLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_goToQueueScreenButtonLabel1, 0);
    lv_obj_set_y(ui_goToQueueScreenButtonLabel1, 270);
    lv_obj_set_align(ui_goToQueueScreenButtonLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_goToQueueScreenButtonLabel1, "ADD TO QUEUE");
    lv_obj_set_style_text_color(ui_goToQueueScreenButtonLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_goToQueueScreenButtonLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_goToQueueScreenButtonLabel1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_addToQueueScreen);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -310);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Step 1: Scan Union Card");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scanCardButton = lv_btn_create(ui_addToQueueScreen);
    lv_obj_set_width(ui_scanCardButton, 167);
    lv_obj_set_height(ui_scanCardButton, 50);
    lv_obj_set_x(ui_scanCardButton, -3);
    lv_obj_set_y(ui_scanCardButton, -235);
    lv_obj_set_align(ui_scanCardButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scanCardButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_scanCardButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scanCardButton, lv_color_hex(0xFF9800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scanCardButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_addToQueueScreen);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, -153);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Step 2: Enter Print Time");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_addToQueueScreen);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -1);
    lv_obj_set_y(ui_Label5, 210);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Step 3: Press Button");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_addToQueueScreen);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -235);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "SCAN NOW");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_addToQueueScreen);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 2);
    lv_obj_set_y(ui_Label7, -281);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "You have 5 seconds to scan your card");

    ui_arcHours = lv_arc_create(ui_addToQueueScreen);
    lv_obj_set_width(ui_arcHours, 150);
    lv_obj_set_height(ui_arcHours, 150);
    lv_obj_set_x(ui_arcHours, -130);
    lv_obj_set_y(ui_arcHours, -30);
    lv_obj_set_align(ui_arcHours, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_arcHours, 0, 36);
    lv_arc_set_value(ui_arcHours, 0);


    ui_arcMinutes = lv_arc_create(ui_addToQueueScreen);
    lv_obj_set_width(ui_arcMinutes, 150);
    lv_obj_set_height(ui_arcMinutes, 150);
    lv_obj_set_x(ui_arcMinutes, 130);
    lv_obj_set_y(ui_arcMinutes, -30);
    lv_obj_set_align(ui_arcMinutes, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_arcMinutes, 0, 59);
    lv_arc_set_value(ui_arcMinutes, 0);


    ui_labelTimerHours = lv_label_create(ui_addToQueueScreen);
    lv_obj_set_width(ui_labelTimerHours, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTimerHours, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTimerHours, -130);
    lv_obj_set_y(ui_labelTimerHours, 45);
    lv_obj_set_align(ui_labelTimerHours, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTimerHours, "hh");

    ui_labelTimerMinutes = lv_label_create(ui_addToQueueScreen);
    lv_obj_set_width(ui_labelTimerMinutes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTimerMinutes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTimerMinutes, 130);
    lv_obj_set_y(ui_labelTimerMinutes, 50);
    lv_obj_set_align(ui_labelTimerMinutes, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTimerMinutes, "min");

    ui_timerAndInfoLabel = lv_label_create(ui_addToQueueScreen);
    lv_obj_set_width(ui_timerAndInfoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timerAndInfoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timerAndInfoLabel, -1);
    lv_obj_set_y(ui_timerAndInfoLabel, -186);
    lv_obj_set_align(ui_timerAndInfoLabel, LV_ALIGN_CENTER);

    ui_labelHours = lv_label_create(ui_addToQueueScreen);
    lv_obj_set_width(ui_labelHours, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelHours, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelHours, -130);
    lv_obj_set_y(ui_labelHours, -30);
    lv_obj_set_align(ui_labelHours, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelHours, "HOURS");
    lv_obj_set_style_text_font(ui_labelHours, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelMinutes = lv_label_create(ui_addToQueueScreen);
    lv_obj_set_width(ui_labelMinutes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelMinutes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelMinutes, 130);
    lv_obj_set_y(ui_labelMinutes, -30);
    lv_obj_set_align(ui_labelMinutes, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelMinutes, "MINUTES");
    lv_obj_set_style_text_font(ui_labelMinutes, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_goToQueueScreenButton, ui_event_goToQueueScreenButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_goToQueueScreenButton1, ui_event_goToQueueScreenButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_goToQueueScreenButtonLabel1, ui_event_goToQueueScreenButtonLabel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_scanCardButton, ui_event_scanCardButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arcHours, ui_event_arcHours, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arcMinutes, ui_event_arcMinutes, LV_EVENT_ALL, NULL);

}
