// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_instructionsScreen_screen_init(void)
{
    ui_instructionsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_instructionsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_goToQueueScreenButton3 = lv_btn_create(ui_instructionsScreen);
    lv_obj_set_width(ui_goToQueueScreenButton3, 400);
    lv_obj_set_height(ui_goToQueueScreenButton3, 50);
    lv_obj_set_x(ui_goToQueueScreenButton3, 0);
    lv_obj_set_y(ui_goToQueueScreenButton3, 340);
    lv_obj_set_align(ui_goToQueueScreenButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_goToQueueScreenButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_goToQueueScreenButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_goToQueueScreenButton3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_goToQueueScreenButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goToQueueScreenButtonLabel3 = lv_label_create(ui_instructionsScreen);
    lv_obj_set_width(ui_goToQueueScreenButtonLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_goToQueueScreenButtonLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_goToQueueScreenButtonLabel3, 0);
    lv_obj_set_y(ui_goToQueueScreenButtonLabel3, 340);
    lv_obj_set_align(ui_goToQueueScreenButtonLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_goToQueueScreenButtonLabel3, "BACK");
    lv_obj_set_style_text_color(ui_goToQueueScreenButtonLabel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_goToQueueScreenButtonLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_goToQueueScreenButtonLabel3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_instructionsScreen);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 0);
    lv_obj_set_y(ui_Label23, -300);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Step 1: Press the \"Add print\" button, \nand follow the instructions there.");
    lv_obj_set_style_text_align(ui_Label23, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_instructionsScreen);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 0);
    lv_obj_set_y(ui_Label24, -50);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24,
                      "Step 3: If you are first or second in queue\nyou can take a printer by first pressing\nyour name in the queue, and then the \nprinter name (Klumpen/Knut).\n\nOBS Always try to find the person first\nin queue if you are second.");
    lv_obj_set_style_text_align(ui_Label24, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_instructionsScreen);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 0);
    lv_obj_set_y(ui_Label25, -200);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Step 2: Wait until a printer is available");
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_instructionsLabel = lv_label_create(ui_instructionsScreen);
    lv_obj_set_width(ui_instructionsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_instructionsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_instructionsLabel, 0);
    lv_obj_set_y(ui_instructionsLabel, -365);
    lv_obj_set_align(ui_instructionsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_instructionsLabel, "INSTRUCTIONS");
    lv_obj_set_style_text_decor(ui_instructionsLabel, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_instructionsLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_instructionsScreen);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 0);
    lv_obj_set_y(ui_Label26, 100);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Step 4: Start printing, good luck!");
    lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_goToQueueScreenButton3, ui_event_goToQueueScreenButton3, LV_EVENT_ALL, NULL);

}
