// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_manageMyPrintsScreen_screen_init(void)
{
    ui_manageMyPrintsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_manageMyPrintsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_backCancelManageMyPrintsButton = lv_btn_create(ui_manageMyPrintsScreen);
    lv_obj_set_width(ui_backCancelManageMyPrintsButton, 400);
    lv_obj_set_height(ui_backCancelManageMyPrintsButton, 50);
    lv_obj_set_x(ui_backCancelManageMyPrintsButton, 0);
    lv_obj_set_y(ui_backCancelManageMyPrintsButton, 340);
    lv_obj_set_align(ui_backCancelManageMyPrintsButton, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_backCancelManageMyPrintsButton, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backCancelManageMyPrintsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_manageMyPrintsScreen);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 0);
    lv_obj_set_y(ui_Label20, 340);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "BACK/CANCEL");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_manageMyPrintsScanButton = lv_btn_create(ui_manageMyPrintsScreen);
    lv_obj_set_width(ui_manageMyPrintsScanButton, 164);
    lv_obj_set_height(ui_manageMyPrintsScanButton, 50);
    lv_obj_set_x(ui_manageMyPrintsScanButton, 0);
    lv_obj_set_y(ui_manageMyPrintsScanButton, -310);
    lv_obj_set_align(ui_manageMyPrintsScanButton, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_manageMyPrintsScanButton, lv_color_hex(0xFF9800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_manageMyPrintsScanButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_manageMyPrintsLabel = lv_label_create(ui_manageMyPrintsScreen);
    lv_obj_set_width(ui_manageMyPrintsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_manageMyPrintsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_manageMyPrintsLabel, 0);
    lv_obj_set_y(ui_manageMyPrintsLabel, -365);
    lv_obj_set_align(ui_manageMyPrintsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_manageMyPrintsLabel, "MANAGE MY PRINTS");
    lv_obj_set_style_text_decor(ui_manageMyPrintsLabel, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_manageMyPrintsLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_adminScanLabel1 = lv_label_create(ui_manageMyPrintsScreen);
    lv_obj_set_width(ui_adminScanLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_adminScanLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_adminScanLabel1, 0);
    lv_obj_set_y(ui_adminScanLabel1, -310);
    lv_obj_set_align(ui_adminScanLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_adminScanLabel1, "SCAN NOW");
    lv_obj_set_style_text_color(ui_adminScanLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_adminScanLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_adminScanLabel1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mangeMyPrintsStatusLabel = lv_label_create(ui_manageMyPrintsScreen);
    lv_obj_set_width(ui_mangeMyPrintsStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mangeMyPrintsStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mangeMyPrintsStatusLabel, 0);
    lv_obj_set_y(ui_mangeMyPrintsStatusLabel, -270);
    lv_obj_set_align(ui_mangeMyPrintsStatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mangeMyPrintsStatusLabel, "Please Scan Your Union Card");

    ui_deleteMyPrintsButton = lv_btn_create(ui_manageMyPrintsScreen);
    lv_obj_set_width(ui_deleteMyPrintsButton, 250);
    lv_obj_set_height(ui_deleteMyPrintsButton, 50);
    lv_obj_set_x(ui_deleteMyPrintsButton, 0);
    lv_obj_set_y(ui_deleteMyPrintsButton, -150);
    lv_obj_set_align(ui_deleteMyPrintsButton, LV_ALIGN_CENTER);

    ui_deleteMyPrintsLabel = lv_label_create(ui_manageMyPrintsScreen);
    lv_obj_set_width(ui_deleteMyPrintsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deleteMyPrintsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_deleteMyPrintsLabel, 0);
    lv_obj_set_y(ui_deleteMyPrintsLabel, -150);
    lv_obj_set_align(ui_deleteMyPrintsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_deleteMyPrintsLabel, "DELETE MY PRINTS");
    lv_obj_set_style_text_color(ui_deleteMyPrintsLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_deleteMyPrintsLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_deleteMyPrintsLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_manageMyPrintsScreen);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -2);
    lv_obj_set_y(ui_Label21, -64);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Long press the button above\nto delete all your prints from \nthe queue");
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backCancelManageMyPrintsButton, ui_event_backCancelManageMyPrintsButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_manageMyPrintsScanButton, ui_event_manageMyPrintsScanButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_deleteMyPrintsButton, ui_event_deleteMyPrintsButton, LV_EVENT_ALL, NULL);

}
