// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_queueManagmentScreen_screen_init(void)
{
    ui_queueManagmentScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_queueManagmentScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_queueManagmentScreen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, -365);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "MANAGE QUEUE");
    lv_obj_set_style_text_decor(ui_Label2, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_emptyQueueButton = lv_btn_create(ui_queueManagmentScreen);
    lv_obj_set_width(ui_emptyQueueButton, 400);
    lv_obj_set_height(ui_emptyQueueButton, 50);
    lv_obj_set_x(ui_emptyQueueButton, 0);
    lv_obj_set_y(ui_emptyQueueButton, -270);
    lv_obj_set_align(ui_emptyQueueButton, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_emptyQueueButton, lv_color_hex(0xE23696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_emptyQueueButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_queueManagmentScreen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -270);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "EMPTY ENTIRE QUEUE");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_queueManagmentStatusLabel = lv_label_create(ui_queueManagmentScreen);
    lv_obj_set_width(ui_queueManagmentStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_queueManagmentStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_queueManagmentStatusLabel, 0);
    lv_obj_set_y(ui_queueManagmentStatusLabel, -320);
    lv_obj_set_align(ui_queueManagmentStatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_queueManagmentStatusLabel, "STATUS LABEL");
    lv_obj_set_style_text_font(ui_queueManagmentStatusLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backCancelButton = lv_btn_create(ui_queueManagmentScreen);
    lv_obj_set_width(ui_backCancelButton, 400);
    lv_obj_set_height(ui_backCancelButton, 50);
    lv_obj_set_x(ui_backCancelButton, 0);
    lv_obj_set_y(ui_backCancelButton, 340);
    lv_obj_set_align(ui_backCancelButton, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_backCancelButton, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backCancelButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_queueManagmentScreen);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 0);
    lv_obj_set_y(ui_Label10, 340);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "BACK/CANCEL");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_queueManagmentScreen);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 0);
    lv_obj_set_y(ui_Label19, -225);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "You must hold down the button, to empty the queue");

    lv_obj_add_event_cb(ui_emptyQueueButton, ui_event_emptyQueueButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backCancelButton, ui_event_backCancelButton, LV_EVENT_ALL, NULL);

}
