// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Queue_hueue_screen_init(void)
{
    ui_Queue_hueue = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Queue_hueue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Printer1 = lv_label_create(ui_Queue_hueue);
    lv_obj_set_width(ui_Printer1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Printer1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Printer1, 0);
    lv_obj_set_y(ui_Printer1, -370);
    lv_obj_set_align(ui_Printer1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Printer1, "Klumpen");
    lv_obj_add_flag(ui_Printer1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_decor(ui_Printer1, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Printer1, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Printer2 = lv_label_create(ui_Queue_hueue);
    lv_obj_set_width(ui_Printer2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Printer2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Printer2, 0);
    lv_obj_set_y(ui_Printer2, -290);
    lv_obj_set_align(ui_Printer2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Printer2, "Knut");
    lv_obj_set_style_text_decor(ui_Printer2, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Printer2, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_printerspot1 = lv_label_create(ui_Queue_hueue);
    lv_obj_set_width(ui_printerspot1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_printerspot1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_printerspot1, 0);
    lv_obj_set_y(ui_printerspot1, -330);
    lv_obj_set_align(ui_printerspot1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_printerspot1, "Placeholder 1");
    lv_obj_set_style_text_font(ui_printerspot1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_printerspot2 = lv_label_create(ui_Queue_hueue);
    lv_obj_set_width(ui_printerspot2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_printerspot2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_printerspot2, 0);
    lv_obj_set_y(ui_printerspot2, -250);
    lv_obj_set_align(ui_printerspot2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_printerspot2, "Placeholder 2");
    lv_obj_set_style_text_font(ui_printerspot2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_queue = lv_label_create(ui_Queue_hueue);
    lv_obj_set_width(ui_queue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_queue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_queue, 0);
    lv_obj_set_y(ui_queue, -150);
    lv_obj_set_align(ui_queue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_queue, "Queue");
    lv_obj_set_style_text_decor(ui_queue, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_queue, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_queuespot1 = lv_label_create(ui_Queue_hueue);
    lv_obj_set_width(ui_queuespot1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_queuespot1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_queuespot1, 0);
    lv_obj_set_y(ui_queuespot1, -100);
    lv_obj_set_align(ui_queuespot1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_queuespot1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_queuespot1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_queuespot1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_queuespot1, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_queuespot2 = lv_label_create(ui_Queue_hueue);
    lv_obj_set_width(ui_queuespot2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_queuespot2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_queuespot2, 0);
    lv_obj_set_y(ui_queuespot2, -50);
    lv_obj_set_align(ui_queuespot2, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_queuespot2, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_queuespot3 = lv_label_create(ui_Queue_hueue);
    lv_obj_set_width(ui_queuespot3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_queuespot3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_queuespot3, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_queuespot3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_queuespot3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_queuespot3, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_queuespot4 = lv_label_create(ui_Queue_hueue);
    lv_obj_set_width(ui_queuespot4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_queuespot4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_queuespot4, 0);
    lv_obj_set_y(ui_queuespot4, 50);
    lv_obj_set_align(ui_queuespot4, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_queuespot4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_queuespot4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_queuespot4, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_queuespot5 = lv_label_create(ui_Queue_hueue);
    lv_obj_set_width(ui_queuespot5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_queuespot5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_queuespot5, 0);
    lv_obj_set_y(ui_queuespot5, 100);
    lv_obj_set_align(ui_queuespot5, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_queuespot5, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_queuespot5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_queuespot5, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_queuespot6 = lv_label_create(ui_Queue_hueue);
    lv_obj_set_width(ui_queuespot6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_queuespot6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_queuespot6, 0);
    lv_obj_set_y(ui_queuespot6, 150);
    lv_obj_set_align(ui_queuespot6, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_queuespot6, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_queuespot6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_queuespot6, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goToAddQueueScreenButton = lv_btn_create(ui_Queue_hueue);
    lv_obj_set_width(ui_goToAddQueueScreenButton, 400);
    lv_obj_set_height(ui_goToAddQueueScreenButton, 50);
    lv_obj_set_x(ui_goToAddQueueScreenButton, 0);
    lv_obj_set_y(ui_goToAddQueueScreenButton, 270);
    lv_obj_set_align(ui_goToAddQueueScreenButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_goToAddQueueScreenButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_goToAddQueueScreenButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_goToAddQueueScreenButtonLabel = lv_label_create(ui_Queue_hueue);
    lv_obj_set_width(ui_goToAddQueueScreenButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_goToAddQueueScreenButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_goToAddQueueScreenButtonLabel, 0);
    lv_obj_set_y(ui_goToAddQueueScreenButtonLabel, 270);
    lv_obj_set_align(ui_goToAddQueueScreenButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_goToAddQueueScreenButtonLabel, "ADD PRINT");
    lv_obj_set_style_text_color(ui_goToAddQueueScreenButtonLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_goToAddQueueScreenButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_goToAddQueueScreenButtonLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goToAddQueueScreenButton1 = lv_btn_create(ui_Queue_hueue);
    lv_obj_set_width(ui_goToAddQueueScreenButton1, 400);
    lv_obj_set_height(ui_goToAddQueueScreenButton1, 50);
    lv_obj_set_x(ui_goToAddQueueScreenButton1, 0);
    lv_obj_set_y(ui_goToAddQueueScreenButton1, 340);
    lv_obj_set_align(ui_goToAddQueueScreenButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_goToAddQueueScreenButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_goToAddQueueScreenButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_updateButton = lv_imgbtn_create(ui_Queue_hueue);
    lv_imgbtn_set_src(ui_updateButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_31439854, NULL);
    lv_imgbtn_set_src(ui_updateButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_updateButton, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_updateButton, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_updateButton, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_updateButton, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_updateButton, 33);
    lv_obj_set_width(ui_updateButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_updateButton, 222);
    lv_obj_set_y(ui_updateButton, -380);
    lv_obj_set_align(ui_updateButton, LV_ALIGN_CENTER);

    ui_queueLength = lv_label_create(ui_Queue_hueue);
    lv_obj_set_width(ui_queueLength, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_queueLength, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_queueLength, 0);
    lv_obj_set_y(ui_queueLength, 205);
    lv_obj_set_align(ui_queueLength, LV_ALIGN_CENTER);
    lv_label_set_text(ui_queueLength, "Queue length: X");
    lv_obj_set_style_text_color(ui_queueLength, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_queueLength, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_adminButton = lv_btn_create(ui_Queue_hueue);
    lv_obj_set_width(ui_adminButton, 72);
    lv_obj_set_height(ui_adminButton, 32);
    lv_obj_set_x(ui_adminButton, -190);
    lv_obj_set_y(ui_adminButton, -370);
    lv_obj_set_align(ui_adminButton, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_adminButton, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_adminButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_adminLabel = lv_label_create(ui_Queue_hueue);
    lv_obj_set_width(ui_adminLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_adminLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_adminLabel, -190);
    lv_obj_set_y(ui_adminLabel, -370);
    lv_obj_set_align(ui_adminLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_adminLabel, "Admin");
    lv_obj_set_style_text_color(ui_adminLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_adminLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_adminLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Printer1, ui_event_Printer1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_queuespot1, ui_event_queuespot1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_queuespot2, ui_event_queuespot2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_goToAddQueueScreenButton, ui_event_goToAddQueueScreenButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_goToAddQueueScreenButton1, ui_event_goToAddQueueScreenButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_updateButton, ui_event_updateButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_adminButton, ui_event_adminButton, LV_EVENT_ALL, NULL);

}
