// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Queue_hueue_screen_init(void)
{
    ui_Queue_hueue = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Queue_hueue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Printer1 = lv_label_create(ui_Queue_hueue);
    lv_obj_set_width(ui_Printer1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Printer1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Printer1, 0);
    lv_obj_set_y(ui_Printer1, -370);
    lv_obj_set_align(ui_Printer1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Printer1, "Printer Bert");
    lv_obj_set_style_text_decor(ui_Printer1, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Printer1, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Printer2 = lv_label_create(ui_Queue_hueue);
    lv_obj_set_width(ui_Printer2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Printer2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Printer2, 0);
    lv_obj_set_y(ui_Printer2, -290);
    lv_obj_set_align(ui_Printer2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Printer2, "Printer Knut");
    lv_obj_set_style_text_decor(ui_Printer2, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Printer2, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_printerspot1 = lv_label_create(ui_Queue_hueue);
    lv_obj_set_width(ui_printerspot1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_printerspot1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_printerspot1, 0);
    lv_obj_set_y(ui_printerspot1, -330);
    lv_obj_set_align(ui_printerspot1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_printerspot1, "Alexander staberg-sand");
    lv_obj_set_style_text_font(ui_printerspot1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_printerspot2 = lv_label_create(ui_Queue_hueue);
    lv_obj_set_width(ui_printerspot2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_printerspot2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_printerspot2, 0);
    lv_obj_set_y(ui_printerspot2, -250);
    lv_obj_set_align(ui_printerspot2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_printerspot2, "Placeholder 1 placeholder 1");
    lv_obj_set_style_text_font(ui_printerspot2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_queue = lv_label_create(ui_Queue_hueue);
    lv_obj_set_width(ui_queue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_queue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_queue, 0);
    lv_obj_set_y(ui_queue, -150);
    lv_obj_set_align(ui_queue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_queue, "Queue");
    lv_obj_set_style_text_font(ui_queue, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_queuespot1 = lv_label_create(ui_Queue_hueue);
    lv_obj_set_width(ui_queuespot1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_queuespot1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_queuespot1, 0);
    lv_obj_set_y(ui_queuespot1, -100);
    lv_obj_set_align(ui_queuespot1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_queuespot1, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_queuespot2 = lv_label_create(ui_Queue_hueue);
    lv_obj_set_width(ui_queuespot2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_queuespot2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_queuespot2, 0);
    lv_obj_set_y(ui_queuespot2, -50);
    lv_obj_set_align(ui_queuespot2, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_queuespot2, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_queuespot3 = lv_label_create(ui_Queue_hueue);
    lv_obj_set_width(ui_queuespot3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_queuespot3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_queuespot3, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_queuespot3, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_queuespot4 = lv_label_create(ui_Queue_hueue);
    lv_obj_set_width(ui_queuespot4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_queuespot4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_queuespot4, 0);
    lv_obj_set_y(ui_queuespot4, 50);
    lv_obj_set_align(ui_queuespot4, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_queuespot4, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

}
