// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Queue_hueue
void ui_Queue_hueue_screen_init(void);
lv_obj_t * ui_Queue_hueue;
void ui_event_Printer1(lv_event_t * e);
lv_obj_t * ui_Printer1;
lv_obj_t * ui_Printer2;
lv_obj_t * ui_printerspot1;
lv_obj_t * ui_printerspot2;
lv_obj_t * ui_queue;
void ui_event_queuespot1(lv_event_t * e);
lv_obj_t * ui_queuespot1;
lv_obj_t * ui_queuespot2;
lv_obj_t * ui_queuespot3;
lv_obj_t * ui_queuespot4;
lv_obj_t * ui_queuespot5;
lv_obj_t * ui_queuespot6;
void ui_event_goToAddQueueScreenButton(lv_event_t * e);
lv_obj_t * ui_goToAddQueueScreenButton;
lv_obj_t * ui_goToAddQueueScreenButtonLabel;
void ui_event_goToAddQueueScreenButton1(lv_event_t * e);
lv_obj_t * ui_goToAddQueueScreenButton1;
void ui_event_updateButton(lv_event_t * e);
lv_obj_t * ui_updateButton;


// SCREEN: ui_addToQueueScreen
void ui_addToQueueScreen_screen_init(void);
lv_obj_t * ui_addToQueueScreen;
void ui_event_goToQueueScreenButton(lv_event_t * e);
lv_obj_t * ui_goToQueueScreenButton;
lv_obj_t * ui_goToQueueScreenButtonLabel;
void ui_event_goToQueueScreenButton1(lv_event_t * e);
lv_obj_t * ui_goToQueueScreenButton1;
void ui_event_goToQueueScreenButtonLabel1(lv_event_t * e);
lv_obj_t * ui_goToQueueScreenButtonLabel1;
lv_obj_t * ui_Label3;
void ui_event_scanCardButton(lv_event_t * e);
lv_obj_t * ui_scanCardButton;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
void ui_event_arcHours(lv_event_t * e);
lv_obj_t * ui_arcHours;
void ui_event_arcMinutes(lv_event_t * e);
lv_obj_t * ui_arcMinutes;
lv_obj_t * ui_labelTimerHours;
lv_obj_t * ui_labelTimerMinutes;
lv_obj_t * ui_timerAndInfoLabel;
lv_obj_t * ui_labelHours;
lv_obj_t * ui_labelMinutes;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_1953216864[1] = {&ui_img_31439854};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Printer1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        printer1Click(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        printer1LongClick(e);
    }
}
void ui_event_queuespot1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        queueSpot1Click(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        queueSpot1LongClick(e);
    }
}
void ui_event_goToAddQueueScreenButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_addToQueueScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_addToQueueScreen_screen_init);
    }
}
void ui_event_goToAddQueueScreenButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_addToQueueScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_addToQueueScreen_screen_init);
    }
}
void ui_event_updateButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        updateButtonEventAction(e);
    }
}
void ui_event_goToQueueScreenButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Queue_hueue, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Queue_hueue_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        cancelButton(e);
    }
}
void ui_event_goToQueueScreenButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        addPrintToQueueButton(e);
    }
}
void ui_event_goToQueueScreenButtonLabel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        addPrintToQueueButton(e);
    }
}
void ui_event_scanCardButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        scanCardButtonAction(e);
    }
}
void ui_event_arcHours(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        arcHoursEventIncrement(e);
    }
}
void ui_event_arcMinutes(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        arcMinutesEventIncrement(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Queue_hueue_screen_init();
    ui_addToQueueScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Queue_hueue);
}
