// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Queue_hueue
void ui_Queue_hueue_screen_init(void);
lv_obj_t * ui_Queue_hueue;
void ui_event_Printer1(lv_event_t * e);
lv_obj_t * ui_Printer1;
void ui_event_Printer2(lv_event_t * e);
lv_obj_t * ui_Printer2;
lv_obj_t * ui_printerspot1;
lv_obj_t * ui_printerspot2;
lv_obj_t * ui_queue;
void ui_event_queuespot1(lv_event_t * e);
lv_obj_t * ui_queuespot1;
void ui_event_queuespot2(lv_event_t * e);
lv_obj_t * ui_queuespot2;
lv_obj_t * ui_queuespot3;
lv_obj_t * ui_queuespot4;
lv_obj_t * ui_queuespot5;
lv_obj_t * ui_queuespot6;
void ui_event_goToAddQueueScreenButton(lv_event_t * e);
lv_obj_t * ui_goToAddQueueScreenButton;
lv_obj_t * ui_goToAddQueueScreenButtonLabel;
void ui_event_goToAddQueueScreenButton1(lv_event_t * e);
lv_obj_t * ui_goToAddQueueScreenButton1;
void ui_event_updateButton(lv_event_t * e);
lv_obj_t * ui_updateButton;
lv_obj_t * ui_queueLength;
void ui_event_adminButton(lv_event_t * e);
lv_obj_t * ui_adminButton;
lv_obj_t * ui_adminLabel;
lv_obj_t * ui_goToAddQueueScreenButtonLabel1;
void ui_event_goToAddInstructionsScreenButton(lv_event_t * e);
lv_obj_t * ui_goToAddInstructionsScreenButton;
lv_obj_t * ui_adminLabel1;


// SCREEN: ui_addToQueueScreen
void ui_addToQueueScreen_screen_init(void);
lv_obj_t * ui_addToQueueScreen;
void ui_event_goToQueueScreenButton(lv_event_t * e);
lv_obj_t * ui_goToQueueScreenButton;
lv_obj_t * ui_goToQueueScreenButtonLabel;
void ui_event_goToQueueScreenButton1(lv_event_t * e);
lv_obj_t * ui_goToQueueScreenButton1;
void ui_event_goToQueueScreenButtonLabel1(lv_event_t * e);
lv_obj_t * ui_goToQueueScreenButtonLabel1;
lv_obj_t * ui_Label3;
void ui_event_scanCardButton(lv_event_t * e);
lv_obj_t * ui_scanCardButton;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
void ui_event_arcHours(lv_event_t * e);
lv_obj_t * ui_arcHours;
void ui_event_arcMinutes(lv_event_t * e);
lv_obj_t * ui_arcMinutes;
lv_obj_t * ui_labelTimerHours;
lv_obj_t * ui_labelTimerMinutes;
lv_obj_t * ui_timerAndInfoLabel;
lv_obj_t * ui_labelHours;
lv_obj_t * ui_labelMinutes;
lv_obj_t * ui_addPrintLabel;


// SCREEN: ui_adminScreen
void ui_adminScreen_screen_init(void);
lv_obj_t * ui_adminScreen;
void ui_event_backCancelAdminButton(lv_event_t * e);
lv_obj_t * ui_backCancelAdminButton;
lv_obj_t * ui_Label8;
void ui_event_adminScanButton(lv_event_t * e);
lv_obj_t * ui_adminScanButton;
lv_obj_t * ui_addPrintLabel2;
lv_obj_t * ui_adminScanLabel;
void ui_event_adminScreenAddMemberButton(lv_event_t * e);
lv_obj_t * ui_adminScreenAddMemberButton;
lv_obj_t * ui_Label9;
void ui_event_adminScreenQueueManagmentButton(lv_event_t * e);
lv_obj_t * ui_adminScreenQueueManagmentButton;
lv_obj_t * ui_queueManagmentLabel;
lv_obj_t * ui_adminScanStatusLabel;


// SCREEN: ui_addMemberScreen
void ui_addMemberScreen_screen_init(void);
lv_obj_t * ui_addMemberScreen;
lv_obj_t * ui_Label11;
void ui_event_scanMemberCardButton(lv_event_t * e);
lv_obj_t * ui_scanMemberCardButton;
lv_obj_t * ui_Label12;
void ui_event_addMemberButton(lv_event_t * e);
lv_obj_t * ui_addMemberButton;
lv_obj_t * ui_memberScreenKeyboard;
lv_obj_t * ui_Label13;
lv_obj_t * ui_adminCheckBox;
void ui_event_memberNameTextArea(lv_event_t * e);
lv_obj_t * ui_memberNameTextArea;
void ui_event_phoneNumberTextArea(lv_event_t * e);
lv_obj_t * ui_phoneNumberTextArea;
void ui_event_backButton(lv_event_t * e);
lv_obj_t * ui_backButton;
lv_obj_t * ui_backButtonLabel;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Label18;
lv_obj_t * ui_scanMemberInfoLabel;


// SCREEN: ui_queueManagmentScreen
void ui_queueManagmentScreen_screen_init(void);
lv_obj_t * ui_queueManagmentScreen;
lv_obj_t * ui_Label2;
void ui_event_emptyQueueButton(lv_event_t * e);
lv_obj_t * ui_emptyQueueButton;
lv_obj_t * ui_Label1;
lv_obj_t * ui_queueManagmentStatusLabel;
void ui_event_backCancelButton(lv_event_t * e);
lv_obj_t * ui_backCancelButton;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label19;
void ui_event_emptyCurrentlyPrintingButton(lv_event_t * e);
lv_obj_t * ui_emptyCurrentlyPrintingButton;
lv_obj_t * ui_Label22;


// SCREEN: ui_manageMyPrintsScreen
void ui_manageMyPrintsScreen_screen_init(void);
lv_obj_t * ui_manageMyPrintsScreen;
void ui_event_backCancelManageMyPrintsButton(lv_event_t * e);
lv_obj_t * ui_backCancelManageMyPrintsButton;
lv_obj_t * ui_Label20;
void ui_event_manageMyPrintsScanButton(lv_event_t * e);
lv_obj_t * ui_manageMyPrintsScanButton;
lv_obj_t * ui_manageMyPrintsLabel;
lv_obj_t * ui_adminScanLabel1;
lv_obj_t * ui_mangeMyPrintsStatusLabel;
void ui_event_deleteMyPrintsButton(lv_event_t * e);
lv_obj_t * ui_deleteMyPrintsButton;
lv_obj_t * ui_deleteMyPrintsLabel;
lv_obj_t * ui_Label21;


// SCREEN: ui_instructionsScreen
void ui_instructionsScreen_screen_init(void);
lv_obj_t * ui_instructionsScreen;
void ui_event_goToQueueScreenButton3(lv_event_t * e);
lv_obj_t * ui_goToQueueScreenButton3;
lv_obj_t * ui_goToQueueScreenButtonLabel3;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Label25;
lv_obj_t * ui_instructionsLabel;
lv_obj_t * ui_Label26;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_1953216864[1] = {&ui_img_31439854};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Printer1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        printer1Click(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        printer1LongClick(e);
    }
}
void ui_event_Printer2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        printer2Click(e);
    }
}
void ui_event_queuespot1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        queueSpot1Click(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        queueSpot1LongClick(e);
    }
}
void ui_event_queuespot2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        queueSpot2LongClick1(e);
    }
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        queueSpot2EventClick2(e);
    }
}
void ui_event_goToAddQueueScreenButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_addToQueueScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_addToQueueScreen_screen_init);
    }
}
void ui_event_goToAddQueueScreenButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_manageMyPrintsScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_manageMyPrintsScreen_screen_init);
    }
}
void ui_event_updateButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        updateButtonEventAction(e);
    }
}
void ui_event_adminButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_adminScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_adminScreen_screen_init);
    }
}
void ui_event_goToAddInstructionsScreenButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_instructionsScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_instructionsScreen_screen_init);
    }
}
void ui_event_goToQueueScreenButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Queue_hueue, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Queue_hueue_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        cancelButton(e);
    }
}
void ui_event_goToQueueScreenButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        addPrintToQueueButton(e);
    }
}
void ui_event_goToQueueScreenButtonLabel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        addPrintToQueueButton(e);
    }
}
void ui_event_scanCardButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        scanCardButtonAction(e);
    }
}
void ui_event_arcHours(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        arcHoursEventIncrement(e);
    }
}
void ui_event_arcMinutes(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        arcMinutesEventIncrement(e);
    }
}
void ui_event_backCancelAdminButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Queue_hueue, LV_SCR_LOAD_ANIM_OVER_TOP, 500, 0, &ui_Queue_hueue_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        backCancelAdminButtonClick(e);
    }
}
void ui_event_adminScanButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        adminScanButtonClick(e);
    }
}
void ui_event_adminScreenAddMemberButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_addMemberScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_addMemberScreen_screen_init);
    }
}
void ui_event_adminScreenQueueManagmentButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_queueManagmentScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_queueManagmentScreen_screen_init);
    }
}
void ui_event_scanMemberCardButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        scanMemberCardButtonClick(e);
    }
}
void ui_event_addMemberButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        addMemberButtonClick(e);
    }
}
void ui_event_memberNameTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_memberScreenKeyboard,  ui_memberNameTextArea);
    }
    if(event_code == LV_EVENT_CLICKED) {
        memberNameTextAreaClickChangeToNumbers(e);
    }
}
void ui_event_phoneNumberTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_memberScreenKeyboard,  ui_phoneNumberTextArea);
    }
    if(event_code == LV_EVENT_CLICKED) {
        phoneNumberTextAreaClickChangeToNumbers(e);
    }
}
void ui_event_backButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_adminScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_adminScreen_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        backButtonClick(e);
    }
}
void ui_event_emptyQueueButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        emptyQueueButtonClick(e);
    }
}
void ui_event_backCancelButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_adminScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_adminScreen_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        backCancelButtonQueueManagmentClick(e);
    }
}
void ui_event_emptyCurrentlyPrintingButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        emptyCurrentlyPrintingButtonClick(e);
    }
}
void ui_event_backCancelManageMyPrintsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Queue_hueue, LV_SCR_LOAD_ANIM_OVER_TOP, 500, 0, &ui_Queue_hueue_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        backCancelManageMyPrintsButtonClick(e);
    }
}
void ui_event_manageMyPrintsScanButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        manageMyPrintsScanButtonClick(e);
    }
}
void ui_event_deleteMyPrintsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        deleteMyPrintsButtonClick(e);
    }
}
void ui_event_goToQueueScreenButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Queue_hueue, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Queue_hueue_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        cancelButton(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Queue_hueue_screen_init();
    ui_addToQueueScreen_screen_init();
    ui_adminScreen_screen_init();
    ui_addMemberScreen_screen_init();
    ui_queueManagmentScreen_screen_init();
    ui_manageMyPrintsScreen_screen_init();
    ui_instructionsScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Queue_hueue);
}
