// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Queue_hueue
void ui_Queue_hueue_screen_init(void);
extern lv_obj_t * ui_Queue_hueue;
void ui_event_Printer1(lv_event_t * e);
extern lv_obj_t * ui_Printer1;
extern lv_obj_t * ui_Printer2;
extern lv_obj_t * ui_printerspot1;
extern lv_obj_t * ui_printerspot2;
extern lv_obj_t * ui_queue;
void ui_event_queuespot1(lv_event_t * e);
extern lv_obj_t * ui_queuespot1;
void ui_event_queuespot2(lv_event_t * e);
extern lv_obj_t * ui_queuespot2;
extern lv_obj_t * ui_queuespot3;
extern lv_obj_t * ui_queuespot4;
extern lv_obj_t * ui_queuespot5;
extern lv_obj_t * ui_queuespot6;
void ui_event_goToAddQueueScreenButton(lv_event_t * e);
extern lv_obj_t * ui_goToAddQueueScreenButton;
extern lv_obj_t * ui_goToAddQueueScreenButtonLabel;
void ui_event_goToAddQueueScreenButton1(lv_event_t * e);
extern lv_obj_t * ui_goToAddQueueScreenButton1;
void ui_event_updateButton(lv_event_t * e);
extern lv_obj_t * ui_updateButton;
extern lv_obj_t * ui_queueLength;
void ui_event_adminButton(lv_event_t * e);
extern lv_obj_t * ui_adminButton;
extern lv_obj_t * ui_adminLabel;
extern lv_obj_t * ui_goToAddQueueScreenButtonLabel1;
// SCREEN: ui_addToQueueScreen
void ui_addToQueueScreen_screen_init(void);
extern lv_obj_t * ui_addToQueueScreen;
void ui_event_goToQueueScreenButton(lv_event_t * e);
extern lv_obj_t * ui_goToQueueScreenButton;
extern lv_obj_t * ui_goToQueueScreenButtonLabel;
void ui_event_goToQueueScreenButton1(lv_event_t * e);
extern lv_obj_t * ui_goToQueueScreenButton1;
void ui_event_goToQueueScreenButtonLabel1(lv_event_t * e);
extern lv_obj_t * ui_goToQueueScreenButtonLabel1;
extern lv_obj_t * ui_Label3;
void ui_event_scanCardButton(lv_event_t * e);
extern lv_obj_t * ui_scanCardButton;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
void ui_event_arcHours(lv_event_t * e);
extern lv_obj_t * ui_arcHours;
void ui_event_arcMinutes(lv_event_t * e);
extern lv_obj_t * ui_arcMinutes;
extern lv_obj_t * ui_labelTimerHours;
extern lv_obj_t * ui_labelTimerMinutes;
extern lv_obj_t * ui_timerAndInfoLabel;
extern lv_obj_t * ui_labelHours;
extern lv_obj_t * ui_labelMinutes;
extern lv_obj_t * ui_addPrintLabel;
// SCREEN: ui_adminScreen
void ui_adminScreen_screen_init(void);
extern lv_obj_t * ui_adminScreen;
void ui_event_backCancelAdminButton(lv_event_t * e);
extern lv_obj_t * ui_backCancelAdminButton;
extern lv_obj_t * ui_Label8;
void ui_event_adminScanButton(lv_event_t * e);
extern lv_obj_t * ui_adminScanButton;
extern lv_obj_t * ui_addPrintLabel2;
extern lv_obj_t * ui_adminScanLabel;
void ui_event_adminScreenAddMemberButton(lv_event_t * e);
extern lv_obj_t * ui_adminScreenAddMemberButton;
extern lv_obj_t * ui_Label9;
void ui_event_adminScreenQueueManagmentButton(lv_event_t * e);
extern lv_obj_t * ui_adminScreenQueueManagmentButton;
extern lv_obj_t * ui_queueManagmentLabel;
extern lv_obj_t * ui_adminScanStatusLabel;
// SCREEN: ui_addMemberScreen
void ui_addMemberScreen_screen_init(void);
extern lv_obj_t * ui_addMemberScreen;
extern lv_obj_t * ui_Label11;
void ui_event_scanMemberCardButton(lv_event_t * e);
extern lv_obj_t * ui_scanMemberCardButton;
extern lv_obj_t * ui_Label12;
void ui_event_addMemberButton(lv_event_t * e);
extern lv_obj_t * ui_addMemberButton;
extern lv_obj_t * ui_memberScreenKeyboard;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_adminCheckBox;
void ui_event_memberNameTextArea(lv_event_t * e);
extern lv_obj_t * ui_memberNameTextArea;
void ui_event_phoneNumberTextArea(lv_event_t * e);
extern lv_obj_t * ui_phoneNumberTextArea;
void ui_event_backButton(lv_event_t * e);
extern lv_obj_t * ui_backButton;
extern lv_obj_t * ui_backButtonLabel;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_scanMemberInfoLabel;
// SCREEN: ui_queueManagmentScreen
void ui_queueManagmentScreen_screen_init(void);
extern lv_obj_t * ui_queueManagmentScreen;
extern lv_obj_t * ui_Label2;
void ui_event_emptyQueueButton(lv_event_t * e);
extern lv_obj_t * ui_emptyQueueButton;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_queueManagmentStatusLabel;
void ui_event_backCancelButton(lv_event_t * e);
extern lv_obj_t * ui_backCancelButton;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label19;
// SCREEN: ui_manageMyPrintsScreen
void ui_manageMyPrintsScreen_screen_init(void);
extern lv_obj_t * ui_manageMyPrintsScreen;
void ui_event_backCancelManageMyPrintsButton(lv_event_t * e);
extern lv_obj_t * ui_backCancelManageMyPrintsButton;
extern lv_obj_t * ui_Label20;
void ui_event_manageMyPrintsScanButton(lv_event_t * e);
extern lv_obj_t * ui_manageMyPrintsScanButton;
extern lv_obj_t * ui_manageMyPrintsLabel;
extern lv_obj_t * ui_adminScanLabel1;
extern lv_obj_t * ui_mangeMyPrintsStatusLabel;
void ui_event_deleteMyPrintsButton(lv_event_t * e);
extern lv_obj_t * ui_deleteMyPrintsButton;
extern lv_obj_t * ui_deleteMyPrintsLabel;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_31439854);    // assets/update-12-32.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
