// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Queue_hueue
void ui_Queue_hueue_screen_init(void);
extern lv_obj_t * ui_Queue_hueue;
void ui_event_Printer1(lv_event_t * e);
extern lv_obj_t * ui_Printer1;
void ui_event_Printer2(lv_event_t * e);
extern lv_obj_t * ui_Printer2;
extern lv_obj_t * ui_printerspot1;
extern lv_obj_t * ui_printerspot2;
extern lv_obj_t * ui_queue;
void ui_event_queuespot1(lv_event_t * e);
extern lv_obj_t * ui_queuespot1;
void ui_event_queuespot2(lv_event_t * e);
extern lv_obj_t * ui_queuespot2;
extern lv_obj_t * ui_queuespot3;
extern lv_obj_t * ui_queuespot4;
extern lv_obj_t * ui_queuespot5;
extern lv_obj_t * ui_queuespot6;
void ui_event_goToAddQueueScreenButton(lv_event_t * e);
extern lv_obj_t * ui_goToAddQueueScreenButton;
extern lv_obj_t * ui_goToAddQueueScreenButtonLabel;
void ui_event_goToAddQueueScreenButton1(lv_event_t * e);
extern lv_obj_t * ui_goToAddQueueScreenButton1;
void ui_event_updateButton(lv_event_t * e);
extern lv_obj_t * ui_updateButton;
extern lv_obj_t * ui_Label1;
// SCREEN: ui_addToQueueScreen
void ui_addToQueueScreen_screen_init(void);
extern lv_obj_t * ui_addToQueueScreen;
void ui_event_goToQueueScreenButton(lv_event_t * e);
extern lv_obj_t * ui_goToQueueScreenButton;
extern lv_obj_t * ui_goToQueueScreenButtonLabel;
void ui_event_goToQueueScreenButton1(lv_event_t * e);
extern lv_obj_t * ui_goToQueueScreenButton1;
void ui_event_goToQueueScreenButtonLabel1(lv_event_t * e);
extern lv_obj_t * ui_goToQueueScreenButtonLabel1;
extern lv_obj_t * ui_Label3;
void ui_event_scanCardButton(lv_event_t * e);
extern lv_obj_t * ui_scanCardButton;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
void ui_event_arcHours(lv_event_t * e);
extern lv_obj_t * ui_arcHours;
void ui_event_arcMinutes(lv_event_t * e);
extern lv_obj_t * ui_arcMinutes;
extern lv_obj_t * ui_labelTimerHours;
extern lv_obj_t * ui_labelTimerMinutes;
extern lv_obj_t * ui_timerAndInfoLabel;
extern lv_obj_t * ui_labelHours;
extern lv_obj_t * ui_labelMinutes;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_31439854);    // assets/update-12-32.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
