// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Queue_hueue
void ui_Queue_hueue_screen_init(void);
extern lv_obj_t * ui_Queue_hueue;
extern lv_obj_t * ui_Printer1;
extern lv_obj_t * ui_Printer2;
extern lv_obj_t * ui_printerspot1;
extern lv_obj_t * ui_printerspot2;
extern lv_obj_t * ui_queue;
extern lv_obj_t * ui_queuespot1;
extern lv_obj_t * ui_queuespot2;
extern lv_obj_t * ui_queuespot3;
extern lv_obj_t * ui_queuespot4;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
