// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void printer1Click(lv_event_t * e);
void printer1LongClick(lv_event_t * e);
void printer2Click(lv_event_t * e);
void queueSpot1Click(lv_event_t * e);
void queueSpot1LongClick(lv_event_t * e);
void queueSpot2LongClick1(lv_event_t * e);
void queueSpot2EventClick2(lv_event_t * e);
void updateButtonEventAction(lv_event_t * e);
void cancelButton(lv_event_t * e);
void addPrintToQueueButton(lv_event_t * e);
void scanCardButtonAction(lv_event_t * e);
void arcHoursEventIncrement(lv_event_t * e);
void arcMinutesEventIncrement(lv_event_t * e);
void backCancelAdminButtonClick(lv_event_t * e);
void adminScanButtonClick(lv_event_t * e);
void scanMemberCardButtonClick(lv_event_t * e);
void addMemberButtonClick(lv_event_t * e);
void memberNameTextAreaClickChangeToNumbers(lv_event_t * e);
void phoneNumberTextAreaClickChangeToNumbers(lv_event_t * e);
void backButtonClick(lv_event_t * e);
void emptyQueueButtonClick(lv_event_t * e);
void backCancelButtonQueueManagmentClick(lv_event_t * e);
void emptyCurrentlyPrintingButtonClick(lv_event_t * e);
void backCancelManageMyPrintsButtonClick(lv_event_t * e);
void manageMyPrintsScanButtonClick(lv_event_t * e);
void deleteMyPrintsButtonClick(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
