// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "Arduino.h"
#include "string.h"

void Killr(lv_event_t * e)
{
	// Your code here
}

// void scanCardButtonAction(lv_event_t * e)
// {
// 	// Your code here
// }

// void arcHoursEventIncrement(lv_event_t * e)
// {
//
// }

// void arcMinutesEventIncrement(lv_event_t * e)
// {
//
// }

// void addPrintToQueueButton(lv_event_t * e)
// {
// 	// Your code here
// }

// void cancelButton(lv_event_t * e)
// {
// 	// Your code here
// }

// void updateButtonEventAction(lv_event_t * e)
// {
// 	// Your code here
// }

// void queueSpot1Click(lv_event_t * e)
// {
// 	// Your code here
// }

// void queueSpot1LongClick(lv_event_t * e)
// {
// 	// Your code here
// }

// void printer1Click(lv_event_t * e)
// {
// 	// Your code here
// }

// void printer1LongClick(lv_event_t * e)
// {
// 	// Your code here
// }

// void queueSpot2Click(lv_event_t * e)
// {
// 	// Your code here
// }

// void queueSpot2LongClick(lv_event_t * e)
// {
// 	// Your code here
// }

// void printer2Click(lv_event_t * e)
// {
// 	// Your code here
// }

// void printer2LongClick(lv_event_t * e)
// {
// 	// Your code here
// }
