// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_ROLLER1_H
#define _UI_COMP_ROLLER1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Roller1
#define UI_COMP_ROLLER1_ROLLER1 0
#define _UI_COMP_ROLLER1_NUM 1
lv_obj_t * ui_Roller1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
