// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT Roller1

lv_obj_t * ui_Roller1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Roller1;
    cui_Roller1 = lv_roller_create(comp_parent);
    lv_roller_set_options(cui_Roller1, "1: Name\nion 2\nOption 3\nOption 4\nOption 5\nOption 6", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(cui_Roller1, 350);
    lv_obj_set_height(cui_Roller1, 700);
    lv_obj_set_x(cui_Roller1, 41);
    lv_obj_set_y(cui_Roller1, -2);
    lv_obj_set_align(cui_Roller1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(cui_Roller1, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_ROLLER1_NUM);
    children[UI_COMP_ROLLER1_ROLLER1] = cui_Roller1;
    lv_obj_add_event_cb(cui_Roller1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Roller1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Roller1_create_hook(cui_Roller1);
    return cui_Roller1;
}

